Convert waveplot part to new structure

diff --git a/docs/_archives/recipes/scripts/get_slakos b/docs/_archives/recipes/scripts/get_slakos
--- a/docs/_archives/recipes/scripts/get_slakos
+++ b/docs/_archives/recipes/scripts/get_slakos
@@ -1,27 +1,33 @@
 #!/bin/bash
 ################################################################################
-# Downloads and unpacks the Slater-Koster files from dftb.org
+# Downloads and unpacks slako related files from dftb.org
 ################################################################################
 scriptdir="$(dirname $0)"
 root="$scriptdir/.."
 downloaddir="$root/slakos/download"
-downloadfile="$root/slakos/DOWNLOAD_SLAKOS"
+downloadfile="$root/slakos/SLAKO_DOWNLOADS"
 slakourlprefix="http://www.dftb.org/fileadmin/DFTB/public/slako"
 
 echo "Downloading SLAKO archives:"
-for archive in $(cat $downloadfile); do
-  tarname=$(basename $archive)
-  echo "Downloading archive $archive as $tarname"
-  wget -q -O $downloaddir/$tarname $slakourlprefix/$archive
+for remotefile in $(cat $downloadfile); do
+  destdir=$(dirname $remotefile)
+  fname=$(basename $remotefile)
+  mkdir -p $downloaddir/$destdir
+  
+  echo "Downloading $remotefile"
+  echo "wget -q -O $downloaddir/$destdir/$fname $slakourlprefix/$remotefile"
+  wget -q -O $downloaddir/$destdir/$fname $slakourlprefix/$remotefile
   if [ $? -ne 0 ]; then
-    echo "DOWNLOAD FAILED" >&2
+    echo "DOWNLOAD FAILED for$ slakourlprefix/$remotefile" >&2
   fi
-  echo "Unpacking archive $tarname"
-  tar -x -C $downloaddir -J -f $downloaddir/$tarname
-  if [ $? -ne 0 ]; then
-    echo "UNPACKING FAILED" >&2
-    exit
+
+  if [ "$(basename $fname .tar.xz)" != "$fname" ]; then
+    echo "Unpacking archive $fname"
+    tar -x -C $downloaddir/$destdir -J -f $downloaddir/$destdir/$fname
+    if [ $? -ne 0 ]; then
+      echo "UNPACKING FAILED for $downloaddir/$destdir/$fname" >&2
+    fi
+    echo "Removing archive $fname"
+    rm -f $downloaddir/$destdir/$fname
   fi
-  echo "Removing archive $tarname"
-  rm -f $downloaddir/$tarname
 done
